### ISSUE TITLE
it's spelt otaku you dunce

### ISSUE THREAD

**Issue by georgebyrom** [kibiitv/otakoclient#1]
<3

**Comment by TheEvilSocks** [comment]
It's spelled spelled you dunce

**Comment by georgebyrom** [comment]
![image](http://awooo.party/i/z1o0n.png)

**Comment by OxKitsune** [comment]
agreed, fix ur shit

**Comment by georgebyrom** [comment]
agreed with who 🤔

**Comment by georgebyrom** [comment]
engrish

**Comment by OxKitsune** [comment]
thonk? with u silly
ily (>///<)

**Comment by georgebyrom** [comment]
k cool ily2

**Comment by Shibe43** [comment]
stop fucking on this

**Comment by OxKitsune** [comment]
sorry mr shibe

**Comment by Shibe43** [comment]
its ok it keeps popping up in yara its annoying

**Comment by georgebyrom** [comment]
what

**Comment by Shibe43** [comment]
do u know what yara the discord server is the new one

**Comment by georgebyrom** [comment]
yeah i left

**Comment by imRocko** [comment]
can you faggots stop commenting this shit is annoying like holy fuck

**Comment by Shibe43** [comment]
well it keeps popping up every msg on there with a bot

**Comment by OxKitsune** [comment]
sorry rocko-senpai I will stop >m<

**Comment by Shibe43** [comment]
rocko were not fags 
;-;

**Comment by imRocko** [comment]
you are if you keep commenting, if you comment past this you're a retard

so stop please thanks

**Comment by Shibe43** [comment]
im not a fag >.< im already a retard btw

**Comment by titanswift** [comment]
hello im new what is this

**Comment by Shibe43** [comment]
say sorry ill stop

**Comment by imRocko** [comment]
TITAN GO AWAY, STOP COMMENTING.

sorry now stop

**Comment by Shibe43** [comment]
idfk

**Comment by OxKitsune** [comment]
huh?

**Comment by titanswift** [comment]
is this programming chat?

**Comment by Shibe43** [comment]
hi titan

**Comment by OxKitsune** [comment]
yes is chatbox

**Comment by imRocko** [comment]
we could easily make alts on github and spam the server...

**Comment by Shibe43** [comment]
wat

**Comment by imRocko** [comment]
how did this webhook even get set up lmao

**Comment by titanswift** [comment]
interesting when do we start

**Comment by Shibe43** [comment]
ikr rocko i was thinking that

**Comment by imRocko** [comment]
now

**Comment by Shibe43** [comment]
we could spam the server

**Comment by imRocko** [comment]
hi archangel, idk what this is

**Comment by OxKitsune** [comment]
so we're spamming yara now?

**Comment by imRocko** [comment]
technically we are by just talking in here

**Comment by Shibe43** [comment]
me too

**Comment by imRocko** [comment]
since it embeds our messages in yara

**Comment by Shibe43** [comment]
im confused

**Comment by imRocko** [comment]
its pretty annoying

**Comment by OxKitsune** [comment]
wow we are cool boys

**Comment by OxKitsune** [comment]
I cant see it tho feelsbad

**Comment by imRocko** [comment]
@everyone

**Comment by Shibe43** [comment]
it does it lmao

**Comment by imRocko** [comment]
@bin

**Comment by imRocko** [comment]
@bin#0160

**Comment by Shibe43** [comment]
@rocko

**Comment by OxKitsune** [comment]
does that work?
owo

**Comment by titanswift** [comment]
LMAO  how did this even happen, the connection

**Comment by imRocko** [comment]
shit it no work

**Comment by imRocko** [comment]
its a webhook @titanswift

**Comment by OxKitsune** [comment]
damn discordembeds

**Comment by Phanrazak** [comment]
Make it stop already

**Comment by Shibe43** [comment]
we are just chatting on here like its a discord server

**Comment by imRocko** [comment]
hey archangel, i see you saying stop

**Comment by imRocko** [comment]
we're gonna keep going

**Comment by Shibe43** [comment]
stop getting triggered were talking on here

**Comment by imRocko** [comment]
f

**Comment by imRocko** [comment]
f

**Comment by imRocko** [comment]
f

**Comment by imRocko** [comment]
f

**Comment by Shibe43** [comment]
f

**Comment by imRocko** [comment]
f

**Comment by Phanrazak** [comment]
Make it stop Bin!

**Comment by imRocko** [comment]
never

**Comment by imRocko** [comment]
yeah guys, we're not trying to ruin yara, we're just having a conversation

**Comment by OxKitsune** [comment]
bin we are discussing the issue, please fix it ty <3

**Comment by Shibe43** [comment]
smash or pass me

**Comment by OxKitsune** [comment]
pass srry

**Comment by imRocko** [comment]
it just so happens to spam yara at the same time

**Comment by imRocko** [comment]
i'd pass the fuck outta you shibe

**Comment by Shibe43** [comment]
why tho

**Comment by titanswift** [comment]
WEBHOOK OP

**Comment by imRocko** [comment]
you gay

**Comment by OxKitsune** [comment]
yeah not our fault its the guy who set the thingy up on yara's fault

**Comment by OxKitsune** [comment]
ur a doggo

**Comment by imRocko** [comment]
who set this up lol

**Comment by OxKitsune** [comment]
im racist now arent I

**Comment by LonerweebEmilyx** [comment]
O

**Comment by titanswift** [comment]
when bin is sleep

**Comment by OxKitsune** [comment]
oh hi weeb

**Comment by Shibe43** [comment]
yeah who did set this shit up

**Comment by Phanrazak** [comment]
lol

**Comment by Shibe43** [comment]
i just saw msg from it and was like he let me try

**Comment by Phanrazak** [comment]
Who's gonna clean this up? 🤔

**Comment by LonerweebEmilyx** [comment]
Dang this pfp is hawt

**Comment by titanswift** [comment]
SOTP???????

**Comment by Shibe43** [comment]
ikr

**Comment by Shibe43** [comment]
its h0t

**Comment by Phanrazak** [comment]
mfw I commented here more than the Git I contribute to xd

**Comment by Shibe43** [comment]
lmao

**Comment by Ihitko** [comment]
FUCK NIGGERS

**Comment by OxKitsune** [comment]
WOOOOOOOOOOOAH

**Comment by Ihitko** [comment]
Mirai suck my cock

**Comment by Phanrazak** [comment]
Just kill the webhook in the server settings

**Comment by Phanrazak** [comment]
Unless you don't have webhook access. then rip

**Comment by Ihitko** [comment]
Mirai sucks bins cock

**Comment by OxKitsune** [comment]
Ist not a webhook tho its a bot xd

**Comment by Ihitko** [comment]
Mirai is a peice of shit

**Comment by Shibe43** [comment]
https://www.roblox.com/games/195845601/Become-a-Spy-Obby-READ-DESC

**Comment by Ihitko** [comment]
Mirai should die

**Comment by Phanrazak** [comment]
Rip mods then, well, guess I know what not to do in my next server

**Comment by Ihitko** [comment]
https://img.rule34.xxx/images/2025/afc019243adcae4c7ac6e5deefea8b2b.gif

**Comment by Shibe43** [comment]
dont be mean to mirai u shit

**Comment by Phanrazak** [comment]
^

**Comment by LonerweebEmilyx** [comment]
Stfu

**Comment by Ihitko** [comment]
Mirai can suck my left nut

**Comment by Phanrazak** [comment]
It's not a bot. it's a webhook 🤦‍♀️

**Comment by Shibe43** [comment]
ew i pressed on the link

**Comment by Shibe43** [comment]
it was a girl sucking a dick

**Comment by Ihitko** [comment]
Rocko sucka my cocko, no homo

**Comment by Phanrazak** [comment]
If it was 3d, then no. cause fuck 3dpd

**Comment by Ihitko** [comment]
Im rewatching evangelion

**Comment by Shibe43** [comment]
it was 3d

**Comment by Ihitko** [comment]
Episode 4 atn

**Comment by Ihitko** [comment]
Atm*

**Comment by Phanrazak** [comment]
Fuck 3dpd. 2D waifu for life

**Comment by Ihitko** [comment]
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

**Comment by Ihitko** [comment]
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

**Comment by Shibe43** [comment]
stop

**Comment by Ihitko** [comment]
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

**Comment by Phanrazak** [comment]
kys

**Comment by Ihitko** [comment]
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

**Comment by Ihitko** [comment]
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

alright. can we not talk about ending ourselves/self harm/suicide so openly ? any further messages and they'll be deleted

**Comment by georgebyrom** [comment]
im fucking crying people think my github issue is a chatroom lmao

**Comment by Ihitko** [comment]
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

alright. can we not talk about ending ourselves/self harm/suicide so openly ? any further messages and they'll be deleted

**Comment by georgebyrom** [comment]
what dunce set up github issues to post to general anyway

**Comment by georgebyrom** [comment]
@Ihitko can you not

**Comment by Phanrazak** [comment]
I doubt anyone thinks it is, we're just here to shitpost

**Comment by Ihitko** [comment]
any further shitposting in general/going by rules/insulting/mocking will not be met with a warn, but a mute until things settle down

alright. can we not talk about ending ourselves/self harm/suicide so openly ? any further messages and they'll be deleted

**Comment by Shibe43** [comment]
stop

**Comment by Phanrazak** [comment]
Sure

**Comment by Ihitko** [comment]
Give me the toad

**Comment by georgebyrom** [comment]
*gives toad*

**Comment by georgebyrom** [comment]
send friend requests to rinixx#9013 <3 i left yara

**Comment by Shibe43** [comment]
no one cares stfu

**Comment by Ihitko** [comment]
alright. can we not talk about ending ourselves/self harm/suicide so openly ? any further messages and they'll be deleted

**Comment by Shibe43** [comment]
what 
u dumb fuck

**Comment by titanswift** [comment]
???

**Comment by binnysenpai** [comment]
u know its called otako for a reason haHAA

**Comment by binnysenpai** [comment]
<@206761174627385345> hello
